# data.py
"""

season_data = {
        18: [
            {'id': 1, 'name': '17maple', 'slimes': 25, 'zooms': 0},
            {'id': 2, 'name': 'Ainthe', 'slimes': 5, 'zooms': 0},
            {'id': 3, 'name': 'Angel', 'slimes': 6, 'zooms': 0},
            {'id': 4, 'name': 'Aoi', 'slimes': 3, 'zooms': 0},
            {'id': 5, 'name': 'Apeks', 'slimes': 4, 'zooms': 0},
            {'id': 6, 'name': 'Ben', 'slimes': 14, 'zooms': 0},
            {'id': 7, 'name': 'Bruno', 'slimes': 7, 'zooms': 0},
            {'id': 8, 'name': 'Butterfly', 'slimes': 6, 'zooms': 0},
            {'id': 9, 'name': 'CatsOnMars', 'slimes': 9, 'zooms': 0},
            {'id': 10, 'name': 'Chuckno14', 'slimes': 10, 'zooms': 0},
            {'id': 11, 'name': 'Cisco07', 'slimes': 5, 'zooms': 0},
            {'id': 12, 'name': 'CloudExt', 'slimes': 6, 'zooms': 0},
            {'id': 13, 'name': 'Consutron', 'slimes': 5, 'zooms': 0},
            {'id': 14, 'name': 'Dan', 'slimes': 5, 'zooms': 0},
            {'id': 15, 'name': 'Dante', 'slimes': 4, 'zooms': 0},
            {'id': 16, 'name': 'Evian', 'slimes': 10, 'zooms': 0},
            {'id': 17, 'name': 'FenixR', 'slimes': 10, 'zooms': 0},
            {'id': 18, 'name': 'Foxs', 'slimes': 4, 'zooms': 0},
            {'id': 19, 'name': 'Gunther', 'slimes': 7, 'zooms': 0},
            {'id': 20, 'name': 'Idk', 'slimes': 3, 'zooms': 0},
            {'id': 21, 'name': 'Innuviel', 'slimes': 2, 'zooms': 0},
            {'id': 22, 'name': 'JAV_AsaTyr', 'slimes': 7, 'zooms': 0},
            {'id': 23, 'name': 'JAV_Eolf', 'slimes': 3, 'zooms': 0},
            {'id': 24, 'name': 'JAV_Moss', 'slimes': 5, 'zooms': 0},
            {'id': 25, 'name': 'JAV_booyah', 'slimes': 21, 'zooms': 0},
            {'id': 26, 'name': 'Kenshin', 'slimes': 16, 'zooms': 0},
            {'id': 27, 'name': 'Leofarr', 'slimes': 14, 'zooms': 0},
            {'id': 28, 'name': 'Link2D3atH', 'slimes': 31, 'zooms': 0},
            {'id': 29, 'name': 'LoRDKYRaN', 'slimes': 11, 'zooms': 0},
            {'id': 30, 'name': 'Minh', 'slimes': 0, 'zooms': 0},
            {'id': 31, 'name': 'Mixer', 'slimes': 3, 'zooms': 0},
            {'id': 32, 'name': 'Moonman', 'slimes': 11, 'zooms': 0},
            {'id': 33, 'name': 'Myamya36', 'slimes': 9, 'zooms': 0},
            {'id': 34, 'name': 'ReddlsRow', 'slimes': 7, 'zooms': 0},
            {'id': 35, 'name': 'SenorTonto', 'slimes': 6, 'zooms': 0},
            {'id': 36, 'name': 'SolidD', 'slimes': 8, 'zooms': 0},
            {'id': 37, 'name': 'Spikeman', 'slimes': 6, 'zooms': 0},
            {'id': 38, 'name': 'Tachii', 'slimes': 27, 'zooms': 0},
            {'id': 39, 'name': 'Vent', 'slimes': 24, 'zooms': 0},
            {'id': 40, 'name': 'ZZ', 'slimes': 8, 'zooms': 0},
            {'id': 41, 'name': 'daedalus', 'slimes': 3, 'zooms': 0},
            {'id': 42, 'name': 'latvice', 'slimes': 4, 'zooms': 0},
            {'id': 43, 'name': 'luxury777', 'slimes': 10, 'zooms': 0},
            {'id': 44, 'name': 'mUmU', 'slimes': 5, 'zooms': 0},
            {'id': 45, 'name': 'megastone', 'slimes': 0, 'zooms': 0},
            {'id': 46, 'name': 'mumumumu', 'slimes': 1, 'zooms': 0},
            {'id': 47, 'name': 'pulkooo', 'slimes': 9, 'zooms': 0},
            {'id': 48, 'name': 'zero', 'slimes': 7, 'zooms': 0},
            {'id': 49, 'name': 'Aile', 'slimes': 19, 'zooms': 0},
            {'id': 50, 'name': 'Gonb', 'slimes': 0, 'zooms': 0},
            {'id': 51, 'name': 'Levi', 'slimes': 7, 'zooms': 0},
            {'id': 52, 'name': 'Soki', 'slimes': 0, 'zooms': 0},
            {'id': 53, 'name': 'Abyss', 'slimes': 0, 'zooms': 0},
            {'id': 54, 'name': 'Angeled', 'slimes': 1, 'zooms': 0},
            {'id': 55, 'name': 'Ophianne', 'slimes': 00, 'zooms': 0},
        ],
        19: [
            {'id': 1, 'name': '17maple', 'slimes': 14, 'zooms': 0},
            {'id': 2, 'name': 'Ainthe', 'slimes': 9, 'zooms': 0},
            {'id': 3, 'name': 'Angel', 'slimes': 5, 'zooms': 0},
            {'id': 4, 'name': 'Aoi', 'slimes': 3, 'zooms': 0},
            {'id': 5, 'name': 'Apeks', 'slimes': 4, 'zooms': 0},
            {'id': 6, 'name': 'Ben', 'slimes': 21, 'zooms': 0},
            {'id': 7, 'name': 'Bruno', 'slimes': 6, 'zooms': 0},
            {'id': 8, 'name': 'Butterfly', 'slimes': 5, 'zooms': 0},
            {'id': 9, 'name': 'CatsOnMars', 'slimes': 4, 'zooms': 0},
            {'id': 10, 'name': 'Chuckno14', 'slimes': 12, 'zooms': 0},
            {'id': 11, 'name': 'Cisco07', 'slimes': 11, 'zooms': 0},
            {'id': 12, 'name': 'CloudExt', 'slimes': 3, 'zooms': 0},
            {'id': 13, 'name': 'Consutron', 'slimes': 1, 'zooms': 0},
            {'id': 14, 'name': 'Dan', 'slimes': 8, 'zooms': 0},
            {'id': 15, 'name': 'Dante', 'slimes': 6, 'zooms': 0},
            {'id': 16, 'name': 'DipidyDip', 'slimes': 21, 'zooms': 0},
            {'id': 17, 'name': 'Evian', 'slimes': 8, 'zooms': 0},
            {'id': 18, 'name': 'FenixR', 'slimes': 9, 'zooms': 0},
            {'id': 19, 'name': 'Foxs', 'slimes': 8, 'zooms': 0},
            {'id': 20, 'name': 'Gunther', 'slimes': 6, 'zooms': 0},
            {'id': 21, 'name': 'Idk', 'slimes': 6, 'zooms': 0},
            {'id': 22, 'name': 'JAV_AsaTyr', 'slimes': 5, 'zooms': 0},
            {'id': 23, 'name': 'JAV_Eolf', 'slimes': 4, 'zooms': 0},
            {'id': 24, 'name': 'JAV_Moss', 'slimes': 1, 'zooms': 0},
            {'id': 25, 'name': 'JAV_booyah', 'slimes': 7, 'zooms': 0},
            {'id': 26, 'name': 'Kenshin', 'slimes': 25, 'zooms': 0},
            {'id': 27, 'name': 'Leofarr', 'slimes': 8, 'zooms': 0},
            {'id': 28, 'name': 'Link2D3atH', 'slimes': 27, 'zooms': 0},
            {'id': 29, 'name': 'LoRDKYRaN', 'slimes': 17, 'zooms': 0},
            {'id': 30, 'name': 'Minh', 'slimes': 13, 'zooms': 0},
            {'id': 31, 'name': 'Mixer', 'slimes': 7, 'zooms': 0},
            {'id': 32, 'name': 'Moonman', 'slimes': 3, 'zooms': 0},
            {'id': 33, 'name': 'Myamya36', 'slimes': 8, 'zooms': 0},
            {'id': 34, 'name': 'ReddlsRow', 'slimes': 9, 'zooms': 0},
            {'id': 35, 'name': 'SenorTonto', 'slimes': 4, 'zooms': 0},
            {'id': 36, 'name': 'SolidD', 'slimes': 9, 'zooms': 0},
            {'id': 37, 'name': 'Spikeman', 'slimes': 4, 'zooms': 0},
            {'id': 38, 'name': 'Tachii', 'slimes': 21, 'zooms': 0},
            {'id': 39, 'name': 'TeamEpic', 'slimes': 7, 'zooms': 0},
            {'id': 40, 'name': 'Vent', 'slimes': 15, 'zooms': 0},
            {'id': 41, 'name': 'ZZ', 'slimes': 8, 'zooms': 0},
            {'id': 42, 'name': 'daedalus', 'slimes': 5, 'zooms': 0},
            {'id': 43, 'name': 'latvice', 'slimes': 4, 'zooms': 0},
            {'id': 44, 'name': 'luxury777', 'slimes': 9, 'zooms': 0},
            {'id': 45, 'name': 'mUmU', 'slimes': 6, 'zooms': 0},
            {'id': 46, 'name': 'megastone', 'slimes': 0, 'zooms': 0},
            {'id': 47, 'name': 'mumumumu', 'slimes': 0, 'zooms': 0},
            {'id': 48, 'name': 'pulkooo', 'slimes': 7, 'zooms': 0},
            {'id': 49, 'name': 'zero', 'slimes': 36, 'zooms': 0},
            {'id': 50, 'name': 'Aile', 'slimes': 14, 'zooms': 0},
            {'id': 51, 'name': 'Gonb', 'slimes': 2, 'zooms': 0},
            {'id': 52, 'name': 'Levi', 'slimes': 2, 'zooms': 0},
            {'id': 53, 'name': 'Soki', 'slimes': 0, 'zooms': 0},
            {'id': 54, 'name': 'Abyss', 'slimes': 0, 'zooms': 0},
            {'id': 55, 'name': 'Angeled', 'slimes': 0, 'zooms': 0},
            {'id': 56, 'name': 'Ophianne', 'slimes': 0, 'zooms': 0},
        ]
        # ... more seasons and their respective data
    }

def data_format():
    replymsg = '[\n'
    for id in range(1, 58):
        member_dict = {}
        member_dict['id'] = id
        member_dict['name'] = ""
        member_dict['slimes'] = 0
        member_dict['zooms'] = 0
        replymsg += f'{member_dict},\n'

    replymsg += ']'
    print(replymsg)

data_format()"""